baseurl: /demo-site

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      cover_image: "/demo-site/assets/img/posts/placeholder.png"

kramdown:
  syntax_highlighter: rouge